spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
      url: jdbc:postgresql://localhost:5432/jobstart
      username: postgres
      password: pgadmin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false

server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: never
